version: '3.8'

services:
  auth:
    container_name: "BM_auth"
    env_file: ./BM_authService/.env
    build:
      context: ./BM_authService
    depends_on:
      - auth_db
    ports:
      - ${AUTH_HOST}:${AUTH_PORT}
  auth_db:
    image: postgres:17
    container_name: "BM_auth_db"
    env_file: ./BM_authService/.env
    volumes:
      - ./BM_authService/config/pg:/etc/postgres:ro
      - ./BM_authService/postgres-data:/var/lib/postgresql/data
    command: ["postgres", "-c", "config_file=/etc/postgres/postgresql.conf"]
  auth_redis:
    image: redis:7.4.2
    container_name: "BM_auth_redis"
    env_file:
      - ./BM_authService/.env
    volumes:
      - ./BM_authService/config/redis:/etc/redis:ro
    command: "/etc/redis/redis.conf"

#  app:
#    container_name: "BM_app"
#    env_file:
#      - ./BM_fileService/.env
#    build:
#      context: ./BM_fileService
#    ports:
#      - ${APP_HOST}:${APP_PORT}

  minio:
    image: minio/minio
    container_name: "minio"
    env_file:
      - ./BM_fileService/.env
    volumes:
      - ./BM_fileService/minio-data:/var/lib/minio/data

